@extends('layouts.adminApp')


@section('styles')
    <style>
        .pagination {
            margin: 0; /* Hilangkan margin default */
        }
        .table-responsive .pagination {
            justify-content: flex-end; /* Posisikan pagination di kanan */
        }
        
    </style>


@endsection

@section('content')
    <div class="container-fluid">
        <h1 class="h3 mb-4 text-gray-800"><i class="fas fa-archive"></i> Archive</h1>



        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Report Archive</h6>
            </div>
            <div class="card-body">

            <!-- Nav Tabs -->
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#stock" class="active nav-link" data-toggle="tab"><i class='fas fa-boxes'> </i> Stock</a>
                </li>

                <li class="nav-item">	
                    <a href="#movement" class="nav-link" data-toggle="tab"><i class='fas fa-chart-bar'></i> Stock Movement</a>
                </li>

                <li class="nav-item">
                    <a href="#minimum" class="nav-link" data-toggle="tab"><i class='fas fa-exclamation-triangle'></i> Minimum Stock</a>
                </li>

                <li class="nav-item">
                    <a href="#receiving" class="nav-link" data-toggle="tab"><i class='fas fa-file-invoice'></i> Receiving</a>
                </li>

                <li class="nav-item">
                    <a href="#dispatching" class="nav-link" data-toggle="tab"><i class='fas fa-file-invoice-dollar'></i> Dispatching</a>
                </li>

                <li class="nav-item">
                    <a href="#adjustment" class="nav-link" data-toggle="tab"><i class='fas fa-tools'></i> Stock Adjustment</a>
                </li>

            </ul>



                <!-- Tab Content -->
                <div class="tab-content pt-3">

                    <!-- stock Tab -->
                    <div class="tab-pane fade show active" id="stock">

                        <div class="table-responsive">
                            <table class="table table-sm table-bordered" id="stockTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        
                                        <th>Report Title</th>
                                        <th>Description</th>
                                    
                                        <th>Generated At</th>
                                        <th>Generated By</th>
                                        <th>Document</th>

                                        <th>Actions</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($stockReports as $stock)
                                        <tr>
                                            <td>{{ ($stockReports->currentPage() - 1) * $stockReports->perPage() + $loop->iteration }}.</td>
                                            <td>{{ $stock->report_title }}</td>
                                            <td>{{ $stock->report_description }}</td>
                                            <td>{{ $stock->created_at ? \Carbon\Carbon::parse($stock->created_at)->timezone('Asia/Jakarta')->format('l, d F Y H:i') : 'N/A' }}</td>
                                            <td>{{ $stock->generated_by }}</td>
                                            <td>
                                                @if ($stock->report_document)
                                                    <a href="{{ asset('storage/' . $stock->report_document) }}" target="_blank">View Document</a>
                                                @else
                                                    No Document
                                                @endif
                                            </td>
                                            <td>
                                                <!-- Edit Button -->
                                                <button class="btn btn-sm btn-primary btn-edit" data-id="{{ $stock->report_id  }}" data-toggle="modal" data-target="#editReportModal">
                                                    <i class="fas fa-edit"></i>
                                                </button>
                                                <!-- Delete Button -->
                                                <button class="btn btn-sm btn-danger btn-delete" data-id="{{ $stock->report_id  }}" data-toggle="modal" data-target="#deleteReportModal">
                                                    <i class="fas fa-trash-alt"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7" class="text-center">No reports available</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>


                        <!-- Info Jumlah Data dan Pagination -->
                        <div class="d-flex justify-content-between align-items-center mt-2">
                            <!-- Info Jumlah Data -->
                            <div class="table">
                                <p class="mb-0">
                                    Showing {{ $stockReports->firstItem() }} to {{ $stockReports->lastItem() }} of {{ $stockReports->total() }} entries
                                </p>
                            </div>

                            <!-- Laravel Pagination -->
                            <div>
                                {{ $stockReports->links('pagination::simple-bootstrap-4') }}
                            </div>
                        </div>

                    </div>

                    <!-- movement Tab -->
                    <div class="tab-pane fade show" id="movement">
                        <div class="table-responsive">
                                <table class="table table-sm table-bordered" id="movementTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($stockMovementReports as $movement)
                                            <tr>
                                                <td>{{ ($stockMovementReports->currentPage() - 1) * $stockMovementReports->perPage() + $loop->iteration }}.</td>
                                                <td>{{ $movement->report_title }}</td>
                                                <td>{{ $movement->report_description }}</td>
                                                <td>{{ $movement->created_at ? \Carbon\Carbon::parse($movement->created_at)->timezone('Asia/Jakarta')->format('l, d F Y H:i') : 'N/A' }}</td>
                                                <td>{{ $movement->generated_by }}</td>
                                                <td>
                                                    @if ($movement->report_document)
                                                        <a href="{{ asset('storage/' . $movement->report_document) }}" target="_blank">View Document</a>
                                                    @else
                                                        No Document
                                                    @endif
                                                </td>
                                                <td>
                                                    <!-- Edit Button -->
                                                    <button class="btn btn-sm btn-primary btn-edit" data-id="{{ $movement->report_id  }}" data-toggle="modal" data-target="#editReportModal">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    <!-- Delete Button -->
                                                    <button class="btn btn-sm btn-danger btn-delete" data-id="{{ $movement->report_id  }}" data-toggle="modal" data-target="#deleteReportModal">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7" class="text-center">No Stock Movement Reports Available</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                      

                            <!-- Info Jumlah Data dan Pagination -->
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <!-- Info Jumlah Data -->
                                <div class="table">
                                    <p class="mb-0">
                                        Showing {{ $stockMovementReports->firstItem() }} to {{ $stockMovementReports->lastItem() }} of {{ $stockMovementReports->total() }} entries
                                    </p>
                                </div>

                                <!-- Laravel Pagination -->
                                <div>
                                    {{ $stockMovementReports->links('pagination::simple-bootstrap-4') }}
                                </div>
                            </div>

            
                        </div>
                    </div>

                    <!-- minimum Tab -->
                    <div class="tab-pane fade show" id="minimum">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="minimumTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($stockMinimumReports as $minimum)
                                            <tr>
                                                <td>{{ ($stockMinimumReports->currentPage() - 1) * $stockMinimumReports->perPage() + $loop->iteration }}.</td>
                                                <td>{{ $minimum->report_title }}</td>
                                                <td>{{ $minimum->report_description }}</td>
                                                <td>{{ $minimum->created_at ? \Carbon\Carbon::parse($minimum->created_at)->timezone('Asia/Jakarta')->format('l, d F Y H:i') : 'N/A' }}</td>
                                                <td>{{ $minimum->generated_by }}</td>
                                                <td>
                                                    @if ($minimum->report_document)
                                                        <a href="{{ asset('storage/' . $minimum->report_document) }}" target="_blank">View Document</a>
                                                    @else
                                                        No Document
                                                    @endif
                                                </td>
                                                <td>
                                                    <!-- Edit Button -->
                                                    <button class="btn btn-sm btn-primary btn-edit" data-id="{{ $minimum->report_id  }}" data-toggle="modal" data-target="#editReportModal">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    <!-- Delete Button -->
                                                    <button class="btn btn-sm btn-danger btn-delete" data-id="{{ $minimum->report_id  }}" data-toggle="modal" data-target="#deleteReportModal">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7" class="text-center">No Stock Minimum Reports Available</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                           

                            <!-- Info Jumlah Data dan Pagination -->
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <!-- Info Jumlah Data -->
                                <div class="table">
                                    <p class="mb-0">
                                        Showing {{ $stockMinimumReports->firstItem() }} to {{ $stockMinimumReports->lastItem() }} of {{ $stockMinimumReports->total() }} entries
                                    </p>
                                </div>

                                <!-- Laravel Pagination -->
                                <div>
                                    {{ $stockMinimumReports->links('pagination::simple-bootstrap-4') }}
                                </div>
                            </div>

            
                        </div>
                    </div>

                    <!-- receiving Tab -->
                    <div class="tab-pane fade show" id="receiving">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="receivingTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($receivingReports as $receiving)
                                            <tr>
                                                <td>{{ ($receivingReports->currentPage() - 1) * $receivingReports->perPage() + $loop->iteration }}.</td>
                                                <td>{{ $receiving->report_title }}</td>
                                                <td>{{ $receiving->report_description }}</td>
                                                <td>{{ $receiving->created_at ? \Carbon\Carbon::parse($receiving->created_at)->timezone('Asia/Jakarta')->format('l, d F Y H:i') : 'N/A' }}</td>
                                                <td>{{ $receiving->generated_by }}</td>
                                                <td>
                                                    @if ($receiving->report_document)
                                                        <a href="{{ asset('storage/' . $receiving->report_document) }}" target="_blank">View Document</a>
                                                    @else
                                                        No Document
                                                    @endif
                                                </td>
                                                <td>
                                                    <!-- Edit Button -->
                                                    <button class="btn btn-sm btn-primary btn-edit" data-id="{{ $receiving->report_id  }}" data-toggle="modal" data-target="#editReportModal">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    <!-- Delete Button -->
                                                    <button class="btn btn-sm btn-danger btn-delete" data-id="{{ $receiving->report_id  }}" data-toggle="modal" data-target="#deleteReportModal">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7" class="text-center">No Receiving Reports Available</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                           

                            <!-- Info Jumlah Data dan Pagination -->
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <!-- Info Jumlah Data -->
                                <div class="table">
                                    <p class="mb-0">
                                        Showing {{ $receivingReports->firstItem() }} to {{ $receivingReports->lastItem() }} of {{ $receivingReports->total() }} entries
                                    </p>
                                </div>

                                <!-- Laravel Pagination -->
                                <div>
                                    {{ $receivingReports->links('pagination::simple-bootstrap-4') }}
                                </div>
                            </div>

            
                        </div>
                    </div>

                    <!-- dispatching Tab -->
                    <div class="tab-pane fade show" id="dispatching">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="dispatchingTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($dispatchingReports as $dispatching)
                                            <tr>
                                                <td>{{ ($dispatchingReports->currentPage() - 1) * $dispatchingReports->perPage() + $loop->iteration }}.</td>
                                                <td>{{ $dispatching->report_title }}</td>
                                                <td>{{ $dispatching->report_description }}</td>
                                                <td>{{ $dispatching->created_at ? \Carbon\Carbon::parse($dispatching->created_at)->timezone('Asia/Jakarta')->format('l, d F Y H:i') : 'N/A' }}</td>
                                                <td>{{ $dispatching->generated_by }}</td>
                                                <td>
                                                    @if ($dispatching->report_document)
                                                        <a href="{{ asset('storage/' . $dispatching->report_document) }}" target="_blank">View Document</a>
                                                    @else
                                                        No Document
                                                    @endif
                                                </td>
                                                <td>
                                                    <!-- Edit Button -->
                                                    <button class="btn btn-sm btn-primary btn-edit" data-id="{{ $dispatching->report_id  }}" data-toggle="modal" data-target="#editReportModal">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    <!-- Delete Button -->
                                                    <button class="btn btn-sm btn-danger btn-delete" data-id="{{ $dispatching->report_id  }}" data-toggle="modal" data-target="#deleteReportModal">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7" class="text-center">No Dispatching Reports Available</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                           

                            <!-- Info Jumlah Data dan Pagination -->
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <!-- Info Jumlah Data -->
                                <div class="table">
                                    <p class="mb-0">
                                        Showing {{ $dispatchingReports->firstItem() }} to {{ $dispatchingReports->lastItem() }} of {{ $dispatchingReports->total() }} entries
                                    </p>
                                </div>

                                <!-- Laravel Pagination -->
                                <div>
                                    {{ $dispatchingReports->links('pagination::simple-bootstrap-4') }}
                                </div>
                            </div>

            
                        </div>
                    </div>
               
                    <!-- adjustment Tab -->
                    <div class="tab-pane fade show" id="adjustment">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="adjustmentTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($adjustmentReports as $adjustment)
                                            <tr>
                                                <td>{{ ($adjustmentReports->currentPage() - 1) * $adjustmentReports->perPage() + $loop->iteration }}.</td>
                                                <td>{{ $adjustment->report_title }}</td>
                                                <td>{{ $adjustment->report_description }}</td>
                                                <td>{{ $adjustment->created_at ? \Carbon\Carbon::parse($adjustment->created_at)->timezone('Asia/Jakarta')->format('l, d F Y H:i') : 'N/A' }}</td>
                                                <td>{{ $adjustment->generated_by }}</td>
                                                <td>
                                                    @if ($adjustment->report_document)
                                                        <a href="{{ asset('storage/' . $adjustment->report_document) }}" target="_blank">View Document</a>
                                                    @else
                                                        No Document
                                                    @endif
                                                </td>
                                                <td>
                                                    <!-- Edit Button -->
                                                    <button class="btn btn-sm btn-primary btn-edit" data-id="{{ $adjustment->report_id  }}" data-toggle="modal" data-target="#editReportModal">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    <!-- Delete Button -->
                                                    <button class="btn btn-sm btn-danger btn-delete" data-id="{{ $adjustment->report_id  }}" data-toggle="modal" data-target="#deleteReportModal">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7" class="text-center">No Stock Adjustment Reports Available</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                           

                            <!-- Info Jumlah Data dan Pagination -->
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <!-- Info Jumlah Data -->
                                <div class="table">
                                    <p class="mb-0">
                                        Showing {{ $adjustmentReports->firstItem() }} to {{ $adjustmentReports->lastItem() }} of {{ $adjustmentReports->total() }} entries
                                    </p>
                                </div>

                                <!-- Laravel Pagination -->
                                <div>
                                    {{ $adjustmentReports->links('pagination::simple-bootstrap-4') }}
                                </div>
                            </div>

            
                        </div>
                    </div>
            

                </div>
        </div>
    </div>


                    <!-- Add Report Modal -->
                    <div class="modal fade" id="addReportModal" tabindex="-1" role="dialog" aria-labelledby="addReportModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form method="POST" action="{{ route('reports.store') }}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="addReportModalLabel">Add New Report</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="report_title">Report Title :</label>
                                            <input type="text" class="form-control" id="report_title" name="report_title" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="report_description">Description :</label>
                                            <textarea class="form-control" id="report_description" name="report_description" rows="3" required></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="report_document">Upload Document :</label>
                                            <input type="file" class="form-control-file" id="report_document" name="report_document" accept=".pdf,.doc,.docx,.xlsx,.jpg,.png">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-primary">Save Report</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Edit Report Modal -->
                    <div class="modal fade" id="editReportModal" tabindex="-1" role="dialog" aria-labelledby="editReportModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form id="editReportForm" method="POST" action="" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="editReportModalLabel">Edit Report</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="edit_report_title" class="font-weight-bold">Report Title :</label>
                                            <input type="text" class="form-control" id="edit_report_title" name="report_title" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="edit_report_description" class="font-weight-bold">Description :</label>
                                            <textarea class="form-control" id="edit_report_description" name="report_description" rows="3" required></textarea>
                                        </div>
        
                                        <label class="font-weight-bold">Replace Document :</label>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input @error('report_document') is-invalid @enderror" name="report_document" id="edit_report_document" accept=".pdf,.doc,.docx,.xlsx,.jpg,.png">
                                            <label class="custom-file-label" for="customFile">Choose file</label>
                                        </div>
                              


                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-primary">Update Report</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Delete Report Modal -->
                    <div class="modal fade" id="deleteReportModal" tabindex="-1" role="dialog" aria-labelledby="deleteReportModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form id="deleteReportForm" method="POST" action="">
                                    @csrf
                                    @method('DELETE')
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteReportModalLabel">Delete Report</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">

                                            <p><span class="text-primary"> {{ Auth::user()->name }}</span>, are you sure you want to delete "<strong><span id="deleteReportTitle"></span></strong>" ?</p>
                                            <div class="alert alert-danger">
                                            <span class="text-danger"><i class="fas fa-exclamation-triangle"></i> <strong>WARNING</strong></span>
                                            <p class="text-danger"><small>This action cannot be undone, the selected product data will be permanently deleted !</small></p>
                                            </div>
                                            
                                            
                                            <div class="form-group form-check">
                                                <label class="form-check-label">
                                                <input class="form-check-input" type="checkbox" name="remember" required> I agree to the Terms & Conditions.
                                                <div class="valid-feedback">Valid.</div>
                                                <div class="invalid-feedback">Check this box to continue.</div>
                                                </label>
                                            </div>



                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
    </div>


<!-- Scripts -->
@section('scripts')

    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('#stockTable').DataTable({
                "paging": false, // Nonaktifkan pagination bawaan DataTables
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#movementTable').DataTable({
                "paging": false, // Nonaktifkan pagination bawaan DataTables
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#minimumTable').DataTable({
                "paging": false, // Nonaktifkan pagination bawaan DataTables
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#receivingTable').DataTable({
                "paging": false, // Nonaktifkan pagination bawaan DataTables
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
    
    <script>
        $(document).ready(function() {
            $('#dispatchingTable').DataTable({
                "paging": false, // Nonaktifkan pagination bawaan DataTables
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

        <script>
        $(document).ready(function() {
            $('#adjustmentTable').DataTable({
                "paging": false, // Nonaktifkan pagination bawaan DataTables
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

    <!-- Datatable -->
    <script>
        $(document).ready(function() {

            // Tampilkan SweetAlert jika ada session flash message
            @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success',
                    text: '{{ session('success') }}',
                    confirmButtonText: 'OK'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: '{{ session('error') }}',
                    confirmButtonText: 'OK'
                });
            @endif

            // Handle click event on "EDIT" button
            $('.btn-edit').on('click', function() {
                const reportId = $(this).data('id'); // Ambil ID report dari tombol

                // Lakukan permintaan AJAX ke server
                $.ajax({
                    url: `/reports/show/${reportId}`, // URL rute Laravel untuk mendapatkan detail report
                    method: 'GET',
                    success: function(data) {
                        // Isi modal dengan data report
                        $('#edit_report_title').val(data.report_title);
                        $('#edit_report_description').val(data.report_description);

                        // Set action URL untuk form edit
                        $('#editReportForm').attr('action', `/reports/update/${reportId}`);

                        // Tampilkan modal
                        $('#editReportModal').modal('show');
                    },
                    error: function(xhr) {
                        alert('Failed to fetch report details. Please try again.');
                    }
                });
            });

            // Handle click event on "DELETE" button
            $('.btn-delete').on('click', function() {
                const reportId = $(this).data('id'); // Ambil ID report dari tombol
                const reportTitle = $(this).closest('tr').find('td:nth-child(2)').text(); // Ambil judul report dari tabel

                // Set action URL untuk form delete
                const deleteUrl = `/reports/delete/${reportId}`;
                $('#deleteReportForm').attr('action', deleteUrl);

                // Tampilkan judul report di modal
                $('#deleteReportTitle').text(reportTitle);
            });


            // Add the following code if you want the name of the file appear on select
            $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });


        });
    </script>
@endsection


@endsection