@extends('layouts.adminApp')


@section('styles')
    <style>
        .pagination {
            margin: 0; /* Hilangkan margin default */
        }
        .table-responsive .pagination {
            justify-content: flex-end; /* Posisikan pagination di kanan */
        }
        
        .table-responsive {
            overflow-x: auto;
            min-height: .01%;
        }
        #receivingHeaderTable {
            width: 100% !important;
            table-layout: auto;
            word-break: break-word;
        }
        .dataTables_wrapper .dataTables_paginate {
            margin-top: 1rem;
        }

        .table-responsive {
            overflow-x: auto;
            position: relative;
        }
        .table-responsive .dropdown-menu {
            position: absolute !important;
            will-change: transform;
        }
        
    </style>


@endsection

@section('content')
    <div class="container-fluid">
        <h1 class="h3 mb-4 text-gray-800"><i class="fas fa-archive"></i> ARCHIVE</h1>



        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">REPORT ARCHIVE</h6>
            </div>
            <div class="card-body">

            <!-- Nav Tabs -->
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#stock" class="active nav-link" data-toggle="tab"><i class='fas fa-boxes'> </i> Stock</a>
                </li>

                <li class="nav-item">	
                    <a href="#movement" class="nav-link" data-toggle="tab"><i class='fas fa-chart-bar'></i> Stock Movement</a>
                </li>

                <li class="nav-item">
                    <a href="#minimum" class="nav-link" data-toggle="tab"><i class='fas fa-exclamation-triangle'></i> Minimum Stock</a>
                </li>

                <li class="nav-item">
                    <a href="#receiving" class="nav-link" data-toggle="tab"><i class='fas fa-file-invoice'></i> Receiving</a>
                </li>

                <li class="nav-item">
                    <a href="#dispatching" class="nav-link" data-toggle="tab"><i class='fas fa-file-invoice-dollar'></i> Dispatching</a>
                </li>

                <li class="nav-item">
                    <a href="#adjustment" class="nav-link" data-toggle="tab"><i class='fas fa-tools'></i> Stock Adjustment</a>
                </li>

            </ul>



                <!-- Tab Content -->
                <div class="tab-content pt-3">

                    <!-- stock Tab -->
                    <div class="tab-pane fade show active" id="stock">

                        <div class="table-responsive">
                            <table class="table table-sm table-bordered" id="stockTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        
                                        <th>Report Title</th>
                                        <th>Description</th>
                                    
                                        <th>Generated At</th>
                                        <th>Generated By</th>
                                        <th>Document</th>

                                        <th>Actions</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>

                            </table>
                        </div>
                    </div>

                    <!-- movement Tab -->
                    <div class="tab-pane fade show" id="movement">
                        <div class="table-responsive">
                                <table class="table table-sm table-bordered" id="movementTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>

                                </table>
                      
                        </div>
                    </div>

                    <!-- minimum Tab -->
                    <div class="tab-pane fade show" id="minimum">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="minimumTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                        
                        </div>
                    </div>

                    <!-- receiving Tab -->
                    <div class="tab-pane fade show" id="receiving">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="receivingTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                           
                        </div>
                    </div>

                    <!-- dispatching Tab -->
                    <div class="tab-pane fade show" id="dispatching">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="dispatchingTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                        </div>
                    </div>
               
                    <!-- adjustment Tab -->
                    <div class="tab-pane fade show" id="adjustment">
                        <div class="table-responsive">
                            
                                <table class="table table-sm table-bordered" id="adjustmentTable" width="100%" cellspacing="0">
                                     <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Report Title</th>
                                            <th>Description</th>
                                            <th>Generated At</th>
                                            <th>Generated By</th>
                                            <th>Document</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                        </div>
                    </div>
            

                </div>
        </div>
    </div>


                    <!-- Add Report Modal -->
                    <div class="modal fade" id="addReportModal" tabindex="-1" role="dialog" aria-labelledby="addReportModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form method="POST" action="{{ route('reports.store') }}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="addReportModalLabel">Add New Report</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="report_title">Report Title :</label>
                                            <input type="text" class="form-control" id="report_title" name="report_title" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="report_description">Description :</label>
                                            <textarea class="form-control" id="report_description" name="report_description" rows="3" required></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="report_document">Upload Document :</label>
                                            <input type="file" class="form-control-file" id="report_document" name="report_document" accept=".pdf,.doc,.docx,.xlsx,.jpg,.png">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-primary">Save Report</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Edit Report Modal -->
                    <div class="modal fade" id="editReportModal" tabindex="-1" role="dialog" aria-labelledby="editReportModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form id="editReportForm" method="POST" action="" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="editReportModalLabel">Edit Report</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="edit_report_title" class="font-weight-bold">Report Title :</label>
                                            <input type="text" class="form-control" id="edit_report_title" name="report_title" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="edit_report_description" class="font-weight-bold">Description :</label>
                                            <textarea class="form-control" id="edit_report_description" name="report_description" rows="3" required></textarea>
                                        </div>
        
                                        <label class="font-weight-bold">Replace Document :</label>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input @error('report_document') is-invalid @enderror" name="report_document" id="edit_report_document" accept=".pdf,.doc,.docx,.xlsx,.jpg,.png">
                                            <label class="custom-file-label" for="customFile">Choose file</label>
                                        </div>
                              


                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-primary">Update Report</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- Delete Report Modal -->
                    <div class="modal fade" id="deleteReportModal" tabindex="-1" role="dialog" aria-labelledby="deleteReportModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form id="deleteReportForm" method="POST" action="">
                                    @csrf
                                    @method('DELETE')
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteReportModalLabel">Delete Report</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">

                                            <p><span class="text-primary"> {{ Auth::user()->name }}</span>, are you sure you want to delete <br>"<strong><span id="deleteReportTitle"></span></strong>" ?</p>
                                            <div class="alert alert-danger">
                                            <span class="text-danger"><i class="fas fa-exclamation-triangle"></i> <strong>WARNING</strong></span>
                                            <p class="text-danger"><small>This action cannot be undone, the selected Report data will be permanently deleted !</small></p>
                                            </div>
                                            
                                            
                                            <div class="form-group form-check">
                                                <label class="form-check-label">
                                                <input class="form-check-input" type="checkbox" name="remember" required> I agree to the Terms & Conditions.
                                                <div class="valid-feedback">Valid.</div>
                                                <div class="invalid-feedback">Check this box to continue.</div>
                                                </label>
                                            </div>



                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
    </div>


<!-- Scripts -->
@section('scripts')

    <!-- Page level plugins -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
    <!-- DataTables core -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- DataTables Responsive (setelah DataTables utama) -->
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/responsive.bootstrap4.min.js"></script>

    <!-- Datatable -->
    <script>
        $(document).ready(function() {
            $('#stockTable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: '{{ route("archive.stock.datatable") }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'report_title', name: 'report_title' },
                    { data: 'report_description', name: 'report_description' },
                    { data: 'created_at', name: 'created_at',
                        render: function(data) {
                            return data ? moment(data).format('dddd, DD MMMM YYYY HH:mm') : 'N/A';
                        }
                    },
                    { data: 'generated_by', name: 'generated_by' },
                    { data: 'document', name: 'document', orderable: false, searchable: false },
                    { data: 'actions', name: 'actions', orderable: false, searchable: false }
                ],
                order: [[3, 'desc']]
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#movementTable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: '{{ route("archive.movement.datatable") }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'report_title', name: 'report_title' },
                    { data: 'report_description', name: 'report_description' },
                    { data: 'created_at', name: 'created_at',
                        render: function(data) {
                            return data ? moment(data).format('dddd, DD MMMM YYYY HH:mm') : 'N/A';
                        }
                    },
                    { data: 'generated_by', name: 'generated_by' },
                    { data: 'document', name: 'document', orderable: false, searchable: false },
                    { data: 'actions', name: 'actions', orderable: false, searchable: false }
                ],
                order: [[3, 'desc']]
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#minimumTable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: '{{ route("archive.minimum.datatable") }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'report_title', name: 'report_title' },
                    { data: 'report_description', name: 'report_description' },
                    { data: 'created_at', name: 'created_at',
                        render: function(data) {
                            return data ? moment(data).format('dddd, DD MMMM YYYY HH:mm') : 'N/A';
                        }
                    },
                    { data: 'generated_by', name: 'generated_by' },
                    { data: 'document', name: 'document', orderable: false, searchable: false },
                    { data: 'actions', name: 'actions', orderable: false, searchable: false }
                ],
                order: [[3, 'desc']]
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#receivingTable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: '{{ route("archive.receiving.datatable") }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'report_title', name: 'report_title' },
                    { data: 'report_description', name: 'report_description' },
                    { data: 'created_at', name: 'created_at',
                        render: function(data) {
                            return data ? moment(data).format('dddd, DD MMMM YYYY HH:mm') : 'N/A';
                        }
                    },
                    { data: 'generated_by', name: 'generated_by' },
                    { data: 'document', name: 'document', orderable: false, searchable: false },
                    { data: 'actions', name: 'actions', orderable: false, searchable: false }
                ],
                order: [[3, 'desc']]
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#dispatchingTable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: '{{ route("archive.dispatching.datatable") }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'report_title', name: 'report_title' },
                    { data: 'report_description', name: 'report_description' },
                    { data: 'created_at', name: 'created_at',
                        render: function(data) {
                            return data ? moment(data).format('dddd, DD MMMM YYYY HH:mm') : 'N/A';
                        }
                    },
                    { data: 'generated_by', name: 'generated_by' },
                    { data: 'document', name: 'document', orderable: false, searchable: false },
                    { data: 'actions', name: 'actions', orderable: false, searchable: false }
                ],
                order: [[3, 'desc']]
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#adjustmentTable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: '{{ route("archive.adjustment.datatable") }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false },
                    { data: 'report_title', name: 'report_title' },
                    { data: 'report_description', name: 'report_description' },
                    { data: 'created_at', name: 'created_at',
                        render: function(data) {
                            return data ? moment(data).format('dddd, DD MMMM YYYY HH:mm') : 'N/A';
                        }
                    },
                    { data: 'generated_by', name: 'generated_by' },
                    { data: 'document', name: 'document', orderable: false, searchable: false },
                    { data: 'actions', name: 'actions', orderable: false, searchable: false }
                ],
                order: [[3, 'desc']]
            });
        });
    </script>




 
    <script>
        $(document).ready(function() {

            // Tampilkan SweetAlert jika ada session flash message
            @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success',
                    text: '{{ session('success') }}',
                    confirmButtonText: 'OK'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: '{{ session('error') }}',
                    confirmButtonText: 'OK'
                });
            @endif

            // Handle click event on "EDIT" button
            $(document).on('click', '.btn-edit', function() {
                const reportId = $(this).data('id'); // Ambil ID report dari tombol

                // Lakukan permintaan AJAX ke server
                $.ajax({
                    url: `/reports/show/${reportId}`, // URL rute Laravel untuk mendapatkan detail report
                    method: 'GET',
                    success: function(data) {
                        // Isi modal dengan data report
                        $('#edit_report_title').val(data.report_title);
                        $('#edit_report_description').val(data.report_description);

                        // Set action URL untuk form edit
                        $('#editReportForm').attr('action', `/reports/update/${reportId}`);

                        // Tampilkan modal
                        $('#editReportModal').modal('show');
                    },
                    error: function(xhr) {
                        alert('Failed to fetch report details. Please try again.');
                    }
                });
            });

            // Handle click event on "DELETE" button
            $(document).on('click', '.btn-delete', function() {
                const reportId = $(this).data('id'); // Ambil ID report dari tombol
                const reportTitle = $(this).closest('tr').find('td:nth-child(2)').text(); // Ambil judul report dari tabel

                // Set action URL untuk form delete
                const deleteUrl = `/reports/delete/${reportId}`;
                $('#deleteReportForm').attr('action', deleteUrl);

                // Tampilkan judul report di modal
                $('#deleteReportTitle').text(reportTitle);
            });


            // Add the following code if you want the name of the file appear on select
            $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });


        });
    </script>
@endsection


@endsection