<!DOCTYPE html>
<html>
<head>
    <title>Dispatching Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        table.kop, table.kop td {
            border: none !important;
            border-collapse: collapse !important;
        }
    </style>
</head>
<body>
        <div class="header">

        <!-- Kop Surat -->
        <table class="kop" width="100%" style="margin-bottom:20px;">
            <tr>
                <td style="width:80px;vertical-align:top;">
                    @if($company && $company->company_img)
                        <img src="{{ public_path('storage/'.$company->company_img) }}" alt="Logo" style="height:70px;">
                    @endif
                </td>
                <td style="text-align:center;">
                    <strong style="font-size:1.3em;">{{ $company->company_name ?? '' }}</strong><br>
                    <span>{{ $company->company_address ?? '' }}</span><br>
                    <span>Phone : {{ $company->company_phone ?? '' }} | Email : {{ $company->company_email ?? '' }}</span>
                </td>

                <td style="width:80px;vertical-align:top;">
                
                </td>
            </tr>
        </table>
        <hr>

            <h2>Dispatching Report</h2>
            <p>
                Generated at : {{ now()->timezone('Asia/Jakarta')->format('l, d F Y H:i') }}
                &nbsp;|&nbsp;
                Generated by : {{ $generatedBy ?? '-' }}
            </p>
        </div>
        
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Change Date</th>
                <th>Product ID</th>
                <th>Product Name</th>
                <th>Change Type</th>
                <th>Quantity Before</th>
                <th>Quantity Changed</th>
                <th>Quantity After</th>
                <th>Changed By</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($dispatchingLogs as $index => $log)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $log->changed_at ? \Carbon\Carbon::parse($log->changed_at)->timezone('Asia/Jakarta')->format('l, d F Y H:i') : 'N/A' }}</td>
                    <td>{{ $log->product->product_id ?? 'N/A' }}</td>
                    <td>{{ $log->product->product_name ?? 'N/A' }}</td>
                    <td>{{ $log->stock_change_type }}</td>
                    <td>{{ $log->qty_before }}</td>
                    <td>{{ $log->qty_changed }}</td>
                    <td>{{ $log->qty_after }}</td>
                    <td>{{ $log->changedBy->name ?? 'System' }}</td>
                    <td>{{ $log->change_note }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>