<!DOCTYPE html>
<html>
<head>
    <title>Stock Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
          table.kop, table.kop td {
            border: none !important;
            border-collapse: collapse !important;
        }
        
    </style>
</head>
<body>
        <div class="header">

    <!-- Kop Surat -->
    <table class="kop" width="100%" style="margin-bottom:20px;">
        <tr>
            <td style="width:80px;vertical-align:top;">
                @if($company && $company->company_img)
                    <img src="{{ public_path('storage/'.$company->company_img) }}" alt="Logo" style="height:70px;">
                @endif
            </td>
            <td style="text-align:center;">
                <strong style="font-size:1.3em;">{{ $company->company_name ?? '' }}</strong><br>
                <span>{{ $company->company_address ?? '' }}</span><br>
                <span>Phone : {{ $company->company_phone ?? '' }} | Email : {{ $company->company_email ?? '' }}</span>
            </td>

            <td style="width:80px;vertical-align:top;">
              
            </td>
        </tr>
    </table>
    <hr>

        <h2>STOCK REPORT</h2>
            <p>
                Generated at : {{ now()->timezone('Asia/Jakarta')->format('l, d F Y H:i') }}
                &nbsp;|&nbsp;
                Generated by : {{ $generatedBy ?? '-' }}
            </p>
        </div>
    
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Product ID</th>
                <th>Product Name</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Unit</th>
                <th>Purchase Price</th>
                <th>Selling Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $index => $product)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $product->product_id }}</td>
                    <td>{{ $product->product_name }}</td>
                    <td>{{ $product->category->category_name ?? 'N/A' }}</td>
                    <td>{{ $product->product_qty }}</td>
                    <td>{{ $product->unit->unit_name ?? 'N/A' }}</td>
                    <td>{{ number_format($product->purchase_price, 2) }}</td>
                    <td>{{ number_format($product->selling_price, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>