@extends('layouts.adminApp')


@section('styles')
    <style>
        .pagination {
            margin: 0; /* Hilangkan margin default */
        }
        .table-responsive .pagination {
            justify-content: flex-end; /* Posisikan pagination di kanan */
        }
        
    </style>


@endsection

@section('content')
<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800"><i class="fas fa-file-alt"></i> Stock Reports</h1>



    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Stock Reports</h6>
        </div>
        <div class="card-body">

            <!-- Button to Add New Report -->
            <a href="{{ route('reports.stockGenerate') }}" class="btn btn-primary mb-3">
                <i class="fas fa-plus"></i> Generate Report
            </a>

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            
                            <th>Report Title</th>
                            <th>Description</th>
                           
                            <th>Generated At</th>
                            <th>Generated By</th>
                            <th>Document</th>

                            <th>Actions</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($reports as $report)
                            <tr>
                                <td>{{ ($reports->currentPage() - 1) * $reports->perPage() + $loop->iteration }}.</td>
                                
                                <td>{{ $report->report_title }}</td>
                                <td>{{ $report->report_description }}</td>

                                <td>{{ $report->created_at }}</td>
                                <td>{{ $report->generated_by }}</td>

                                <td>
                                    @if ($report->report_document)
                                        <a href="{{ asset('storage/' . $report->report_document) }}" target="_blank">View Document</a>
                                    @else
                                        No Document
                                    @endif
                                </td>
                                <td>
                                    <!-- Edit Button -->
                                    <button class="btn btn-sm btn-primary btn-edit" data-id="{{ $report->report_id }}" data-toggle="modal" data-target="#editReportModal">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                    <!-- Delete Button -->
                                    <button class="btn btn-sm btn-danger btn-delete" data-id="{{ $report->report_id }}" data-toggle="modal" data-target="#deleteReportModal">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="text-center">No reports available</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

                <!-- Info Jumlah Data dan Pagination -->
                <div class="d-flex justify-content-between align-items-center mt-2">
                    <!-- Info Jumlah Data -->
                    <div class="table">
                        <p class="mb-0">
                            Showing {{ $reports->firstItem() }} to {{ $reports->lastItem() }} of {{ $reports->total() }} entries
                        </p>
                    </div>

                    <!-- Laravel Pagination -->
                    <div>
                        {{ $reports->links('pagination::simple-bootstrap-4') }}
                    </div>
                </div>
        </div>
    </div>
</div>

<!-- Add Report Modal -->
<div class="modal fade" id="addReportModal" tabindex="-1" role="dialog" aria-labelledby="addReportModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="{{ route('reports.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title" id="addReportModalLabel">Add New Report</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="report_title">Report Title</label>
                        <input type="text" class="form-control" id="report_title" name="report_title" required>
                    </div>
                    <div class="form-group">
                        <label for="report_description">Description</label>
                        <textarea class="form-control" id="report_description" name="report_description" rows="3" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="report_document">Upload Document</label>
                        <input type="file" class="form-control-file" id="report_document" name="report_document" accept=".pdf,.doc,.docx,.xlsx,.jpg,.png">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save Report</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit Report Modal -->
<div class="modal fade" id="editReportModal" tabindex="-1" role="dialog" aria-labelledby="editReportModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="editReportForm" method="POST" action="" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="modal-header">
                    <h5 class="modal-title" id="editReportModalLabel">Edit Report</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="edit_report_title">Report Title</label>
                        <input type="text" class="form-control" id="edit_report_title" name="report_title" required>
                    </div>
                    <div class="form-group">
                        <label for="edit_report_description">Description</label>
                        <textarea class="form-control" id="edit_report_description" name="report_description" rows="3" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="edit_report_document">Upload Document</label>
                        <input type="file" class="form-control-file" id="edit_report_document" name="report_document" accept=".pdf,.doc,.docx,.xlsx,.jpg,.png">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Update Report</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete Report Modal -->
<div class="modal fade" id="deleteReportModal" tabindex="-1" role="dialog" aria-labelledby="deleteReportModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="deleteReportForm" method="POST" action="">
                @csrf
                @method('DELETE')
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteReportModalLabel">Delete Report</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this report?</p>
                    <p><strong>Report Title:</strong> <span id="deleteReportTitle"></span></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>





<!-- Scripts -->
@section('scripts')

    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Datatable -->
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                "paging": false, // Nonaktifkan pagination bawaan DataTables
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });

            // Tampilkan SweetAlert jika ada session flash message
            @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success',
                    text: '{{ session('success') }}',
                    confirmButtonText: 'OK'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: '{{ session('error') }}',
                    confirmButtonText: 'OK'
                });
            @endif

            // Handle click event on "EDIT" button
            $('.btn-edit').on('click', function() {
                const reportId = $(this).data('id'); // Ambil ID report dari tombol

                // Lakukan permintaan AJAX ke server
                $.ajax({
                    url: `/reports/${reportId}/edit`, // URL rute Laravel untuk mendapatkan detail report
                    method: 'GET',
                    success: function(data) {
                        // Isi modal dengan data report
                        $('#edit_report_title').val(data.report_title);
                        $('#edit_report_description').val(data.report_description);

                        // Set action URL untuk form edit
                        $('#editReportForm').attr('action', `/reports-edit/${reportId}`);

                        // Tampilkan modal
                        $('#editReportModal').modal('show');
                    },
                    error: function(xhr) {
                        alert('Failed to fetch report details. Please try again.');
                    }
                });
            });

            // Handle click event on "DELETE" button
            $('.btn-delete').on('click', function() {
                const reportId = $(this).data('id'); // Ambil ID report dari tombol
                const reportTitle = $(this).closest('tr').find('td:nth-child(2)').text(); // Ambil judul report dari tabel

                // Set action URL untuk form delete
                const deleteUrl = `/reports/stock/${reportId}`;
                $('#deleteReportForm').attr('action', deleteUrl);

                // Tampilkan judul report di modal
                $('#deleteReportTitle').text(reportTitle);
            });
        });
    </script>
@endsection


@endsection